import { Token, DexInfo, Network } from './types';

export const NETWORKS: Network[] = [
    {
        name: 'Arbitrum One',
        chainId: 42161,
        rpcUrl: 'https://arb1.arbitrum.io/rpc',
        explorerUrl: 'https://arbiscan.io',
        aavePoolAddressesProvider: '0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb',
        isTestnet: false,
    },
    {
        name: 'Arbitrum Sepolia',
        chainId: 421614,
        rpcUrl: 'https://sepolia-rollup.arbitrum.io/rpc',
        explorerUrl: 'https://sepolia.arbiscan.io',
        aavePoolAddressesProvider: '0x012b6d31c0e04f23471f9fe01bc955c6849971b6',
        isTestnet: true,
    },
];

// Example tokens on Arbitrum network
export const SUPPORTED_TOKENS: Record<number, Token[]> = {
    42161: [
        { name: 'Wrapped Ether', symbol: 'WETH', address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', decimals: 18, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/eth.svg' },
        { name: 'USD Coin', symbol: 'USDC', address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', decimals: 6, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/usdc.svg' },
        { name: 'Tether', symbol: 'USDT', address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9', decimals: 6, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/usdt.svg' },
        { name: 'Dai', symbol: 'DAI', address: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1', decimals: 18, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/dai.svg' },
        { name: 'Wrapped Bitcoin', symbol: 'WBTC', address: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', decimals: 8, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/wbtc.svg' },
    ],
    421614: [
        { name: 'Wrapped Ether', symbol: 'WETH', address: '0x980B6951f8D4547565127AA539Ce5fe6ade2588b', decimals: 18, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/eth.svg' },
        { name: 'USD Coin', symbol: 'USDC', address: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d', decimals: 6, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/usdc.svg' },
        { name: 'Tether', symbol: 'USDT', address: '0x6e09390627936f63f5e6ff635bb21bb3075632d1', decimals: 6, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/usdt.svg' },
        { name: 'Dai', symbol: 'DAI', address: '0x5364a12777d13401044623b2444b1055f446b89c', decimals: 18, logoUrl: 'https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@1a63530be6e374711a8554f31b17e4cb92c25fa5/svg/color/dai.svg' },
    ],
};

// Example DEXes on Arbitrum
export const SUPPORTED_DEXES: DexInfo[] = [
    { name: 'UniswapV3', logoUrl: 'https://raw.githubusercontent.com/uniswap/interface/main/src/assets/svg/logo_white.svg' },
    { name: 'Sushiswap', logoUrl: 'https://raw.githubusercontent.com/sushiswap/art/master/sushi/logo-256x256.png' },
    { name: 'Balancer', logoUrl: 'https://raw.githubusercontent.com/balancer/brand-assets/main/logo/logo-wordmark-light.svg' },
];

export const DEFAULT_CONTRACT_CODE = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.10;

// Minimal Aave V3 Interfaces
interface IPoolAddressesProvider {
    function getPool() external view returns (address);
}

interface IPool {
    function flashLoanSimple(
        address receiverAddress,
        address asset,
        uint256 amount,
        bytes calldata params,
        uint16 referralCode
    ) external;
}

interface IERC20 {
    function approve(address spender, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
}

/**
 * @title FlashLoanArbitrage (Template)
 * @author Gemini
 * @notice This is a template for an Aave V3 flash loan contract.
 * 
 * It provides the basic structure for receiving and repaying a flash loan.
 * The full arbitrage logic will be generated by Gemini when you click
 * "Generate Smart Contract" after configuring your desired assets and DEXes.
 */
contract FlashLoanArbitrage {
    address public owner;
    IPool public immutable POOL;

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    constructor(address _poolAddressesProvider) {
        owner = msg.sender;
        POOL = IPool(IPoolAddressesProvider(_poolAddressesProvider).getPool());
    }

    /**
     * @notice Initiates the flash loan. This function will be fully implemented by Gemini.
     */
    function executeFlashLoan(address _asset, uint256 _amount) external onlyOwner {
        // The address of this contract will be the receiver
        address receiverAddress = address(this);

        // Call the Aave pool to request the flash loan
        // The 'params' argument is unused in this simple case
        // A referral code is not used, so we pass 0
        POOL.flashLoanSimple(receiverAddress, _asset, _amount, bytes(""), 0);
    }

    /**
     * @notice This is the callback function that Aave's Pool will call.
     * @dev It's executed after the loan is received. The generated contract
     *      will contain the arbitrage logic here.
     */
    function executeOperation(
        address asset,
        uint256 amount,
        uint256 premium,
        address initiator,
        bytes calldata params
    ) external returns (bool) {
        // --- Your arbitrage logic will be generated here ---
        // For example:
        // 1. Swap asset on DEX 1
        // 2. Swap back on DEX 2
        // 3. Check for profit

        // Ensure the caller is the Aave V3 Pool
        require(msg.sender == address(POOL), "Caller is not Aave Pool");
        
        // At the end of the operation, the contract must repay the loan + premium.
        uint256 amountToRepay = amount + premium;
        require(IERC20(asset).balanceOf(address(this)) >= amountToRepay, "Insufficient balance for repayment");
        
        // Approve the Aave Pool to pull the funds for repayment
        IERC20(asset).approve(address(POOL), amountToRepay);

        return true;
    }

    // Function to withdraw profits (ERC20 tokens) from the contract
    function withdraw(address _tokenAddress) external onlyOwner {
        IERC20 token = IERC20(_tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (balance > 0) {
            token.transfer(owner, balance);
        }
    }

    // Fallback to receive ETH
    receive() external payable {}
}
`;

export const AAVE_POOL_ADDRESS_PROVIDER_ARBITRUM = "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb";